### ISSUE TITLE
Milestone 1 : Brainstorming

### ISSUE THREAD

**Issue by ellognea** [UBC-MDS/ellognea-ptung-mental-health#1]
- Dataset: Mental Health in Tech Survey
- Question: What factors lead to employees seeking treatment for a mental health condition ?
- Target audience:  Employers
- Response variable: Treatment
- Explanatory variables: Age, Gender, Country, Family history, work_interfere, remote_work, benefits, seek_help, obs_consequence

**Comment by tungpatrick** [comment]
Good work. I think we have most, if not all, of what we wanted down.
