### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/ellognea-ptung-mental-health#15]
Good job overall!

- The writing would benefit from more succinct sentences.
- What does it mean that the user "will be taken to a page with more detailed graphical analysis"? Will the app automatically switch to a new tab or will this page appear underneath the original visualization? It might be a bit intrusive to automatically switch tabs, so it might be better for the visualization to appear underneath if there is enough space (just a minor thought).
- I think your final visualization can become really good! There are some aspects with the sketch that can be improved to get there:
    - Unnecessary to display the formula for how to calculate percentage.
    - Rainbow colormaps are poor choices for continuous data. Good general color map advice can be found [here](https://matplotlib.org/users/colormaps.html) and some of the references talk about the rainbow map in detail in case you're interested.
    - The cursive text is hard to read.
    - It could be a good idea to limit the second page to only display 4 graphs and skip the scrollbar. Both for your own implementation time and to increase clarity to the user by narrowing the focus of the app.

**Comment by ellognea** [comment]
Thank you for the feedback Joel. Much appreciated. 
Just so we don't repeat the same mistake , could you please explain why we got A- in the mechanics section ? Also what did we miss in the reasoning part ?
Thanks again

**Comment by ellognea** [comment]
Many thanks. I appreciate your detailed feedback.
