### ISSUE TITLE
Milestone3 Peer Feedback- Albert & Chao

### ISSUE THREAD

**Issue by chaomander2018** [UBC-MDS/ellognea-ptung-mental-health#31]
Hi Patrick and Opheilia, 
We really love your app!

1. Overall neat look! Very easy to understand and follow.
2. Radio button, and check boxes are good features, all of them work well! No bugs detected. 
3. Great pop-up selector after filtering out the data on the left hand side panel. 
4. Options to add country options. This is a great design.
5. Pre-selected all datapoint prior to user selection, this shows the big pictures, great! 
6. Variable Descriptions are clear and helpful. 

1. It would be great to add some notes when some countries only have singular answer. Users may not to understand at the first glance (e.g. work inference over treatment.)
2. Squeezed charts after switching subgroup option.  Maybe test a couple of times before deployment.

Great job!

Albert and Chao

**Comment by ellognea** [comment]
Thanks for the feedback. We've made the width of the bars consistent. This makes it easier to identity missing categories.
